FROM node:20-alpine

WORKDIR /app

# Install system dependencies if needed (e.g., for some node packages)
RUN apk add --no-cache libc6-compat

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# We don't copy the rest of the files here because they will be mounted as a volume
# for live-reloading in development.

EXPOSE 4000

ENV PORT 4000
ENV HOSTNAME "0.0.0.0"

CMD ["npm", "run", "dev"]
